server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: localhost #Eureka服务端实例名称
  client:
    register-with-eureka: false #是否向Eureka注册自己
    fetch-registry: false #Erueka是为注册中心，不需要检索服务信息;(表示是否从Eureka Server获取注册信息，默认为true。 如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false)
    service-url: #监控页面
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/